services:
  frontend:
    image: mbienaimee/todo-backend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: mbienaimee/todo-backend:latest
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
